### ISSUE TITLE
More Function: Exception

### ISSUE THREAD

**Issue by dannypsnl** [llir/document#4]
@mewmew Do you have time to make a draft?

**Comment by dannypsnl** [comment]
I'm not sure this needs a section, CPS conversion is powerful to do this.

**Comment by mewmew** [comment]
> @mewmew Do you have time to make a draft?

@dannypsnl, a draft of what? :)

**Comment by dannypsnl** [comment]
exception example

**Comment by mewmew** [comment]
> exception example

Right. To be honest, I have quite poor understanding of how exceptions work on the low-level, how it pertains to indirect control flow, etc. So, I don't know how to write the LLVM IR details needed for implementing exception handling.

**Comment by dannypsnl** [comment]
It's tricking in LLVM, https://llvm.org/docs/ExceptionHandling.html, you can reuse C++ implementation with all it's problems or make your one.

**Comment by dannypsnl** [comment]
https://github.com/llir/document/commit/a6d838dcd2fdbf2fb78ee468273bc244a5cc1d09 here throw but no catch

**Comment by dannypsnl** [comment]
done!
